# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: ricferrazleal
google_analytics: UA-39648822-1
title: Tek et al.

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 20

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Tek et al.

description: Some stuff...
author:
  name: Ricardo M. Ferraz Leal
  email: ricleal@gmail.com
  github: ricleal
  twitter: ricferrazleal
  facebook: ricleal
  linkedin: ricleal
  bio: Computer Scientist, Data Analyst, Software Architect
  email_md5: ac2978ac59bb12317324c4a0af421b04
  avatar: /assets/media/bio-photo.jpg

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
  - jekyll-twitter-plugin
